### ISSUE TITLE
problems with installing libtoxcore-racket

### ISSUE THREAD

**Issue by 4DA** [lehitoskin/libtoxcore-racket#6]
raco pkg install libtoxcore-racket:
....

.racket/6.1/pkgs/libtoxcore-racket/test/test.rkt:60:1: set-name!: unbound identifier in module
  in: set-name!
  context...:
   /usr/racket/collects/compiler/cm.rkt:309:0: compile-zo*
   /usr/racket/collects/compiler/cm.rkt:519:26
   /usr/racket/collects/compiler/cm.rkt:512:42
   /usr/racket/collects/compiler/cm.rkt:477:0: maybe-compile-zo
   /usr/racket/collects/compiler/cm.rkt:588:2: do-check
   /usr/racket/collects/compiler/cm.rkt:670:4
   /usr/racket/collects/setup/parallel-do.rkt:420:20: loop

**Comment by lehitoskin** [comment]
I keep forgetting to fix the test file, which @samth so nicely fixed in 1c7af327a77ecb10a9c24b02ae37c5d83cb7993f
